name: Java Build Check

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'

    - name: Build All Entry Points
      run: |
        entry_point_files=$(grep -l -r --include=\*.java "public static void main(String\[\] args)" src)

        if [[ ! -z $entry_point_files ]]; then
        echo "Entry points found:"
          for file in $entry_point_files; do
            echo " - $file"
          done

          javac src/**/*.java
        else
            echo "No entry points were found."
            exit 1
        fi
