name: Java Code Formatter

on:
  push:
    paths:
      - '**.java'
  pull_request:
    paths:
      - '**.java'

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Cache google-java-format
        id: cache-gjf
        uses: actions/cache@v3
        with:
          path: ~/.google-java-format/
          key: google-java-format-1.18.1
          restore-keys: |
            google-java-format-

      - name: Download google-java-format
        if: steps.cache-gjf.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.google-java-format
          wget -O ~/.google-java-format/google-java-format-1.18.1-all-deps.jar https://github.com/google/google-java-format/releases/download/v1.18.1/google-java-format-1.18.1-all-deps.jar

      - name: Format Java code
        run: |
          find . -name "*.java" -exec java -jar ~/.google-java-format/google-java-format-1.18.1-all-deps.jar --replace {} \;

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit add . || echo "No changes to add"
          git commit -m "Format Java code" || echo "No changes to commit"
          git push
